"""Generated by Django 3.2.8 on 2021-10-14 00:33."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """First migration."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarningDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40,
                                          verbose_name='Название')),
                ('type_device', models.CharField(choices=[
                    ('Сирена', 'Сирена'),
                    ('Громкоговоритель', 'Громкоговоритель')
                ], max_length=16,
                    verbose_name='Тип устройста')),
                ('adress_location', models.CharField(
                    max_length=200,
                    verbose_name='Адрес размещения')),
                ('latitude', models.FloatField(max_length=6,
                                               verbose_name='Широта')),
                ('longitude', models.FloatField(
                    max_length=6, verbose_name='Долгота')),
                ('zone_radius', models.IntegerField(
                    max_length=10, verbose_name='Радиус зоны звукопокрытия')),
            ],
            options={
                'verbose_name': 'Устройство оповещения',
                'verbose_name_plural': 'Устройства оповещения',
            },
        ),
    ]
